### ISSUE TITLE
[Feature]: Prevent Write on Containers with custom names

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf-zarr#122]
### What would you like to see added to HDMF-ZARR?

There is not catch/error for writing root containers (files) that have custom names. In order to properly write, the root container's name need to be "root". 

We cannot raise a warning and rename the container due to the fact renaming a container and a builder is not allowed. Raise an error in `write_builder` to prevent incorrect writing.

### What solution would you like?

```
if f_builder.name != ROOT_NAME:
            msg = f"Root builder has name {f_builder.name}. Needs to be {ROOT_NAME}."
            raise ValueError(msg)

```

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

**Comment by mavaylon1** [comment]
I will look back into this before the next release (0.7.0)

**Comment by rly** [comment]
Closing for now because it does not seem to be an issue. I think this came up only in the testing suite where you can have a root builder named something other than "root".

The `NWBFile` schema hardcodes the name to be "root". Writing a builder with a hardcoded name in the schema ignores the actual name of the container and uses the schema name: https://github.com/hdmf-dev/hdmf/blob/be602e51804922e01bcd0e6f89b23873f9e13b4b/src/hdmf/build/objectmapper.py#L1388

On read, the root group is read into a builder with a hardcoded name "root".
